[package]
name = "vocab_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
csv = "1.3.0"
rand = "0.8.5"
rand_core = "0.6.4"
serde = { version = "1.0.188", features = ["derive"] }
